openapi: 3.0.3
x-stoplight:
  id: oyf2pt1k0zz67
info:
  title: home-care-navi-second
  version: '1.0'
  description: ②期のホームケアナビのAPI仕様書
  contact:
    name: 平林直樹
    url: 'https://example.com'
    email: test@example.com
  termsOfService: hogehoge
  license:
    name: MIT
    url: 'https://example.com'
servers:
  - url: 'http://localhost:3000'
    description: 平林直樹
paths:
  /health_check:
    get:
      summary: ヘルスチェック
      tags:
        - health_check
      responses:
        '200':
          description: OK
          headers: {}
      operationId: get-health-check
      description: ヘルスチェック用のエンドポイントです
  /api/v1/auth/validate_token:
    get:
      summary: トークン検証
      operationId: validate_token
      description: 'ヘッダー内のaccess-token,client,expiry,uidを検証する'
      parameters: []
      security:
        - access-token: []
        - client: []
        - expiry: []
        - uid: []
      responses:
        '200':
          $ref: '#/components/responses/AuthSuccess'
        '422':
          $ref: '#/components/responses/Error'
      tags:
        - auth
    parameters: []
  /api/v1/auth:
    post:
      summary: ユーザー新規作成
      operationId: sign_up
      description: ユーザーを新規登録する。typeの値によって、ユーザーの種別(事務所利用者等)が決定する。
      requestBody:
        $ref: '#/components/requestBodies/Registration'
      responses:
        '200':
          $ref: '#/components/responses/AuthSuccess'
        '422':
          $ref: '#/components/responses/Error'
      tags:
        - auth
    parameters: []
  /api/v1/auth/sign_in:
    post:
      summary: ユーザーログイン
      operationId: sign_in
      description: ユーザーログイン
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                session:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                      example: test1@example.com
                      description: メールアドレス
                    password:
                      type: string
                      example: password
                      description: パスワード
                  required:
                    - email
                    - password
                  additionalProperties: false
            examples:
              example-1:
                value:
                  session:
                    email: test1@example.com
                    password: password
          application/xml:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          $ref: '#/components/responses/AuthSuccess'
          additionalProperties: false
      tags:
        - auth
    parameters: []
  /api/v1/auth/sign_out:
    delete:
      summary: 事業所利用者ログアウト
      operationId: sign_out
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                    description: 成功判定
                    readOnly: true
                required:
                  - success
      description: 'ヘッダーに`access-token`,`uid`,`client`必須。ログアウトする。'
      security:
        - access-token: []
        - client: []
        - expiry: []
        - uid: []
      tags:
        - auth
    parameters: []
  /api/v1/offices:
    get:
      summary: 事業所一覧取得
      tags:
        - office
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    - id: 1
                      name: 田中　太郎
                      email: office1@example.com
                      tel: 090-1111-2222
                      postal: '1234567'
                      address: 東京都新宿区市ヶ谷本村町5番1号
                      type: OfficeRepresentative
                      created_at: '2022-08-03T00:06:06.514+09:00'
                      updated_at: '2022-08-03T00:06:06.514+09:00'
                    - id: 2
                      name: 鈴木　次郎
                      email: office2@example.com
                      tel: 080-1234-4444
                      postal: '3210232'
                      address: 栃木県下都賀郡壬生町中泉1-14-2
                      type: OfficeRepresentative
                      created_at: '2022-08-03T00:06:06.514+09:00'
                      updated_at: '2022-08-03T00:06:06.514+09:00'
                    - id: 3
                      name: 加藤　三郎
                      email: office3@example.com
                      tel: 070-1242-1296
                      postal: '0850013'
                      address: 北海道釧路市栄町4519
                      type: OfficeRepresentative
                      created_at: '2022-08-03T00:06:06.514+09:00'
                      updated_at: '2022-08-03T00:06:06.514+09:00'
      operationId: getOffices
      description: 事業所一覧を取得する。
      parameters:
        - schema:
            type: string
            example: 東京 大阪 群馬
          in: query
          name: q
          description: addressを前方一致検索する。OR検索は半角スペースで区切る。
    parameters: []
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: ygtg1gffnd7xu
      type: object
      description: 事業所利用者及び事業所代表者
      properties:
        id:
          type: number
          example: 1
          description: ID
          readOnly: true
        name:
          type: string
          description: 名前
          example: テスト 太郎
        email:
          type: string
          format: email
          example: test@example.com
          description: メールアドレス
        tel:
          type: string
          description: 電話番号
          example: 090-1111-2222
          pattern: '^0[-0-9]{11,12}$'
        postal:
          type: string
          example: '1234567'
          pattern: '^\d{7}$'
          description: 郵便番号
          maxLength: 7
        address:
          type: string
          example: 東京都新宿区市ヶ谷本村町5番1号
          description: 住所
        type:
          type: string
          example: Client
          description: STIによるユーザー識別文字列
        created_at:
          type: string
          format: date-time
          example: '2022-08-03T00:06:06.514+09:00'
          description: 作成日時
        updated_at:
          type: string
          format: date-time
          example: '2022-08-03T00:06:06.514+09:00'
          description: 更新日時
      required:
        - id
        - name
        - email
        - tel
        - postal
        - address
        - type
        - created_at
        - updated_at
  responses:
    AuthSuccess:
      description: ''
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              status:
                type: string
                example: success
                description: successまたはerror
                readOnly: true
              data:
                allOf:
                  - type: object
                    description: 認証情報
                    properties:
                      provider:
                        type: string
                        example: email
                        default: email
                        description: emailやOmniauth等の認証方式
                      uid:
                        type: string
                        format: email
                        example: test1@example.com
                        description: ユーザー識別子
                      allow_password_change:
                        type: boolean
                        default: false
                        description: パスワード変更中判定
                        readOnly: true
                    required:
                      - provider
                      - uid
                      - allow_password_change
                  - $ref: '#/components/schemas/User'
                description: ユーザー及び認証情報
            required:
              - status
              - data
          examples:
            example-1:
              value:
                status: success
                data:
                  provider: email
                  uid: test1@example.com
                  allow_password_change: false
                  id: 1
                  name: テスト 太郎
                  email: test@example.com
                  tel: 090-1111-2222
                  postal: '1234567'
                  address: 東京都新宿区市ヶ谷本村町5番1号
                  type: Client
                  created_at: '2022-08-03T00:06:06.514+09:00'
                  updated_at: '2022-08-03T00:06:06.514+09:00'
      headers:
        access-token:
          schema:
            type: string
            example: 7sbMLu90-fDnajzasuhOTQ
          description: トークン認証に必要なヘッダー(1/4)
        client:
          schema:
            type: string
            example: xJ-BFLHzY_XNMX_cjsQnPw
          description: トークン認証に必要なヘッダー(2/4)
        expiry:
          schema:
            type: number
            example: 1660145125
          description: トークン認証に必要なヘッダー(3/4)
        uid:
          schema:
            type: string
            example: test1@example.com
          description: トークン認証に必要なヘッダー(4/4)
    Error:
      description: Example response
      content:
        application/json:
          schema:
            allOf:
              - properties:
                  status:
                    type: string
                    default: error
                    example: error
                    description: エラーステータス
                    readOnly: true
                required:
                  - status
              - properties:
                  data:
                    type: object
                    description: レスポンスによって異なる
                required:
                  - data
              - properties:
                  errors:
                    type: object
                    required:
                      - full_messages
                    description: エラー情報
                    properties:
                      full_messages:
                        type: array
                        description: すべてのエラーメッセージ
                        items:
                          type: string
                          example: メールアドレスはすでに存在します
                required:
                  - errors
            type: object
          examples:
            example-1:
              value:
                status: error
                data: {}
                errors:
                  full_messages:
                    - メールアドレスはすでに存在します
  requestBodies:
    Registration:
      content:
        application/json:
          schema:
            allOf:
              - properties:
                  registration:
                    type: object
                    required:
                      - name
                      - email
                      - tel
                      - postal
                      - address
                      - password
                      - type
                    properties:
                      name:
                        type: string
                        description: 名前
                        example: テスト 太郎
                      email:
                        type: string
                        format: email
                        example: test@example.com
                        description: メールアドレス
                      tel:
                        type: string
                        description: 電話番号
                        example: 090-1111-2222
                        pattern: '^0[-0-9]{11,12}$'
                      postal:
                        type: string
                        example: '1234567'
                        pattern: '^\d{7}$'
                        description: 郵便番号
                        maxLength: 7
                      address:
                        type: string
                        example: 東京都新宿区市ヶ谷本村町5番1号
                        description: 住所
                      password:
                        type: string
                        example: password
                        description: パスワード
                      type:
                        type: string
                        example: Client
                        description: STIによるユーザー識別文字列
                required:
                  - registration
              - properties:
                  confirm_success_url:
                    type: string
                    format: uri
                    example: 'https://www.home-care-navi-second'
                    description: アカウント登録メールに記載されるURL
                required:
                  - confirm_success_url
            type: object
          examples:
            example-1:
              value:
                registration:
                  name: テスト 太郎
                  email: test@example.com
                  tel: 090-1111-2222
                  postal: '1234567'
                  address: 東京都新宿区市ヶ谷本村町5番1号
                  password: password
                  type: Client
                confirm_success_url: 'https://www.home-care-navi-second'
      description: ''
  parameters:
    access-token:
      name: access-token
      in: header
      required: true
      schema:
        type: string
        example: 7sbMLu90-fDnajzasuhOTQ
      description: トークン認証に必要なヘッダー(1/4)
    client:
      name: client
      in: header
      required: true
      schema:
        type: string
        example: xJ-BFLHzY_XNMX_cjsQnPw
      description: トークン認証に必要なヘッダー(2/4)
    expiry:
      name: expiry
      in: header
      required: true
      schema:
        type: number
        example: 1660145125
      description: トークン認証に必要なヘッダー(3/4)
    uid:
      name: uid
      in: header
      required: true
      schema:
        type: string
        example: test1@example.com
      description: トークン認証に必要なヘッダー(4/4)
  securitySchemes:
    access-token:
      name: access-token
      type: apiKey
      in: header
      description: トークン認証に必要なヘッダー(1/4)
    client:
      name: client
      type: apiKey
      in: header
      description: トークン認証に必要なヘッダー(2/4)
    expiry:
      name: expiry
      type: apiKey
      in: header
      description: トークン認証に必要なヘッダー(3/4)
    uid:
      name: uid
      type: apiKey
      in: header
      description: トークン認証に必要なヘッダー(4/4)
tags:
  - name: auth
    description: 認証
  - name: health_check
    description: ヘルスチェック関連
  - name: office
    description: 事業所
